# -------------------------------
# Travis-CI Configuration
# -------------------------------
# https://docs.travis-ci.com/user/customizing-the-build

sudo: false
language: node_js
node_js:
  - iojs
  - '0.12'
  - '0.10'

# -------------------------------




# -------------------------------
# Branch Whitelist/Blacklist
# -------------------------------

branches:
  only:
    - master
    - /^deploy-.*$/


# -------------------------------




# -------------------------------
# Caching
# -------------------------------

cache:
  directories:
    - node_modules
    - bower_dependencies

# -------------------------------




# -------------------------------
# Pre-Installation
# -------------------------------

before_install:
  - npm install bower -g
  - npm install gulp -g

# -------------------------------




# -------------------------------
# Installation
# -------------------------------

install:
  - npm install

# -------------------------------




# -------------------------------
# Build Matrix
# -------------------------------

matrix:
  fast_finish: true
  allow_failures:
    - node_js: iojs

# -------------------------------




# -------------------------------
# Pre-Build
# -------------------------------

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

# -------------------------------




# -------------------------------
# Build
# -------------------------------
# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step

script:
  - npm test

# -------------------------------




# -------------------------------
# Deployment
# -------------------------------




# https://docs.travis-ci.com/user/customizing-the-build/#Deploying-your-Code
